import type { Chapter } from "./types";

export const chapter13: Chapter = {
  num: 13,
  slug: "improving-accessibility",
  title: "Improving Accessibility",
  titleZh: "提升可访问性",
  officialUrl: "https://nextjs.org/learn/dashboard-app/improving-accessibility",
  summary:
    "⚠️ 开始前：本项目 TypeScript 用 **6.x**（7.0 会让 eslint 报错）；lint 需先按第 6 个知识点配置。用 `useActionState` + 服务端 `safeParse` 做表单校验，并用 `aria-*` 属性让错误既能看见、也能被读出来。",
  goals: [
    "认识可访问性的三类抓手（语义化 HTML、ARIA、错误反馈）",
    "会用 `useActionState` 管理表单状态",
    "会用 zod `safeParse` 返回结构化错误",
    "会用 `aria-describedby` / `aria-live` 让错误可被朗读",
  ],
  points: [
    {
      title: "可访问性（a11y）是什么，为什么要做",
      why: "「对屏幕阅读器友好」往往等价于「结构清晰、语义正确」，顺手也提升代码质量。",
      explain: [
        "可访问性指让**所有人都能用**：使用屏幕阅读器的视障用户、只用键盘的用户、色觉障碍用户等。官方专门有一章讲它，说明这不是可选项。",
        "三类抓手：",
        "- **语义化 HTML**：该用 `<button>` 就别用 `<div>`",
        "- **ARIA 属性**：补充说明元素之间的关系与状态",
        "- **表单校验反馈**：错误必须能被读出来，而不只是变红",
        "自查手段：用 `Tab` 走一遍页面（能到每个可操作元素吗？焦点看得见吗？）、用浏览器无障碍面板看名称与角色、跑 `npm run lint`（Next 的 ESLint 带 `jsx-a11y` 规则）。⚠️ 本项目的 lint **需要先配置**（Next 16 已移除 `next lint`）—— **完整的三步配置写在本章最后一个知识点**「练习：给其余字段补齐错误提示，并跑一次 lint」里。",
      ],
      check: "能说出三种自查方式，并指出页面上至少一个「用 div 冒充按钮」或「图标按钮没有名字」的问题。",
    },
    {
      title: "客户端校验：先了解，再看它的局限",
      why: "浏览器原生校验很好用，但救不了「有人绕过前端」。",
      explain: [
        "给输入框加 `required`，浏览器提交时**原生阻止**并弹提示，不用写一行 JS。课程让你先加上体验一下。",
        "局限很明确：用户可以在开发者工具删掉这个属性，也可以绕过页面直接调接口。**客户端校验是体验优化，服务端校验才是安全底线。**",
        "体验完就**把它删掉**（官方原话：delete the `required` attributes）。这点很关键：只要 `required` 还在，浏览器会在提交前就拦下表单，**服务端 action 根本不会被调用** —— 后面几个知识点要观察的「服务端返回错误 → 界面显示错误」就永远触发不了。",
        "所以课程随后就去掉它，改用 `useActionState` + 服务端校验返回错误 —— 错误信息来自服务端、无法绕过，体验也不差。",
      ],
      code: "// 在 app/ui/invoices/create-form.tsx 里，给金额那个 <input> 先加上 required\n// ⚠️ 体验完就删掉，不要留在代码里（留着会拦住提交，后面看不到服务端错误）\n<input id=\"amount\" name=\"amount\" type=\"number\" step=\"0.01\" required />",
      check: "点提交时空表单被浏览器拦住；能说出「为什么这不够」；然后**把 `required` 删掉**。",
    },
    {
      title: "用 useActionState 管理表单状态",
      why: "它把「上次提交结果」和「提交中」两个状态直接交给你。",
      explain: [
        "⚠️ **先知道（重要）**：这一步和**下一个知识点是连着的**。`useActionState` 会按 `(prevState, formData)` 调用 action，而 `createInvoice` 现在还是旧签名 `(formData)` —— 所以**只做这一步会先报两种错**：类型 `ts(2769)`、以及提交表单时的 `formData.get is not a function`。它们都会在**下一个知识点**（改服务端签名）后消失 —— 建议这两个知识点**连着做**。",
        "`useActionState` 来自 `react`：`const [state, formAction, isPending] = useActionState(action, initialState)`。",
        "- `state`：action 的返回值（如错误信息）",
        "- `formAction`：包装好的函数，直接给 `<form action={formAction}>`",
        "- `isPending`：是否正在提交",
        "因此 `app/ui/invoices/create-form.tsx` 要改成**客户端组件**（顶部 `'use client'`），按钮用 `disabled={isPending}` 并显示 `isPending ? 'Submitting...' : 'Create Invoice'`。",
        "初始状态**必须标注类型**：从 `actions.ts` 引入 `State`，写成 `const initialState: State = { message: null, errors: {} };`。**`: State` 不能省** —— 它决定 `state.errors` 的类型；不标注的话 `state.errors` 会被推断成空对象 `{}`，后面写 `state.errors.customerId` 会报「属性 `customerId` 不存在」。⚠️ `State` 类型要到**下一个知识点**才定义，所以这一步的 import 会先报红，属预期内。",
      ],
      code:
        "// app/ui/invoices/create-form.tsx —— 在第 11 章接好 createInvoice 的那个版本上改：\n// ① 文件最顶部加 'use client'，并让 import 带上 State 类型\n'use client';\n\nimport { useActionState } from 'react';\nimport { createInvoice, State } from '@/app/lib/actions';\n\n// ② 下面 2 行放在组件函数体内部（export default function 的 { } 里）\n//    ⚠️ 类型标注 : State 不能省（见上面讲解）；State 要到下一个知识点才定义\nconst initialState: State = { message: null, errors: {} };\nconst [state, formAction, isPending] = useActionState(createInvoice, initialState);\n\n// ③ 再把 return 里最外层的 <form> 换成这段（中间那些输入框保持不动）\n<form action={formAction}>\n  {/* …… 原来的输入框 …… */}\n  <button type=\"submit\" disabled={isPending}>\n    {isPending ? 'Submitting...' : 'Create Invoice'}\n  </button>\n</form>",
      check: "提交时按钮立刻显示 `Submitting...` 并禁用；结束后恢复。",
      pitfalls: [
        "`useActionState` 从 `react` 导入（React 19）；旧写法 `useFormState`（来自 `react-dom`）已过时。",
        "`initialState` 的形状要与 action 返回值一致，否则渲染错误时取到 undefined。",
      ],
    },
    {
      title: "服务端校验：改签名（加 prevState）+ 用 safeParse 返回错误",
      why: "`parse` 抛错会中断流程、只能靠 error.tsx 兜底；`safeParse` 能把「哪个字段错了」精确送回界面。",
      explain: [
        "⚠️ **先改函数签名（漏了它就会报错）**：把 `createInvoice` 从 `(formData: FormData)` 改成 **`(prevState: State, formData: FormData)`**。参数顺序不能反、也不能少 —— `useActionState` 是按「先传 state、再传表单数据」调用 action 的。漏掉 `prevState`，第一个参数收到的就是**初始 state 对象**（不是 `FormData`），提交时必然抛 `formData.get is not a function`。",
        "定义状态形状：`export type State = { errors?: { customerId?: string[]; amount?: string[]; status?: string[] }; message?: string | null; };`（要与上一个知识点里 `initialState` 的形状一致）。",
        "把 `CreateInvoice.parse(...)` 换成 `safeParse({...})`，判断 `if (!validatedFields.success) { return { errors: validatedFields.error.flatten().fieldErrors, message: '...' }; }`。",
        "`safeParse` 返回**结果对象**而不是抛错，所以校验失败时函数直接 `return` 错误状态，界面用 `state.errors`、`state.message` 分别显示。",
        "顺带改一处：写库的 `catch` 里**从 `throw` 改成 `return { message: ... }`**。既然现在能把错误显示回表单，数据库出错就不该整页崩到 `error.tsx`，而是以 `state.message` 的形式提示用户（官方课程在这一步就是这么改的）。",
      ],
      code:
        "// app/lib/actions.ts —— 在第 12 章那个版本上改：\n// 文件顶部照旧（'use server'、import、FormSchema 都不动），只有 createInvoice 变了：\n// ① 新增 State 类型 ② 函数签名加 prevState ③ parse → safeParse ④ catch 里的 throw 改成 return\n// ⚠️ 第 12 章加的 try/catch 要保留，它包的是下面「写库」那一步\nexport type State = {\n  errors?: {\n    customerId?: string[];\n    amount?: string[];\n    status?: string[];\n  };\n  message?: string | null;\n};\n\nexport async function createInvoice(prevState: State, formData: FormData) {\n  const validatedFields = CreateInvoice.safeParse({\n    customerId: formData.get('customerId'),\n    amount: formData.get('amount'),\n    status: formData.get('status'),\n  });\n\n  if (!validatedFields.success) {\n    return {\n      errors: validatedFields.error.flatten().fieldErrors,\n      message: 'Missing Fields. Failed to Create Invoice.',\n    };\n  }\n\n  const { customerId, amount, status } = validatedFields.data;\n  const amountInCents = Math.round(amount * 100);\n  const date = new Date().toISOString().split('T')[0];\n\n  try {\n    await sql`INSERT INTO invoices (customer_id, amount, status, date)\n      VALUES (${customerId}, ${amountInCents}, ${status}, ${date})`;\n  } catch (error) {\n    // 这里不再 throw，而是 return —— 错误文案通过 state.message 显示回表单\n    return {\n      message: 'Database Error: Failed to Create Invoice.',\n    };\n  }\n\n  revalidatePath('/dashboard/invoices');\n  redirect('/dashboard/invoices');\n}",
      check: "提交空表单后，服务端返回结构化错误（而不是抛异常），界面拿到 `state.errors`。",
    },
    {
      title: "把错误显示出来，并让它能被朗读（aria）",
      why: "视觉上变红只是「一半」的可访问性 —— 错误必须同时以文本与播报的形式存在。",
      explain: [
        "⚠️ **前置检查（否则这两行一写就报错）**：确认「用 useActionState 管理表单状态」那步的两件事都做了 —— `import { createInvoice, State } from '@/app/lib/actions';`、`const initialState: State = { message: null, errors: {} };`。漏了 `: State` 标注，`state.errors` 会被推断成空对象 `{}`，写 `state.errors.customerId` 就报 `Property 'customerId' does not exist on type '{}'`。",
        "⚠️ 服务端上一步已经把错误 `return` 出来了，但**界面不会自己显示**：必须在这里用 `state.errors` / `state.message` 把它渲染出来，否则提交后看起来就像「什么都没发生」（校验确实生效了，只是没人把它画出来）。",
        "按字段渲染错误，并给控件加属性：",
        "- `aria-describedby`：值填错误容器的 id（这里是 `customer-error`），把「这个元素」与「那条错误说明」关联",
        "- `aria-invalid`：值为 true 或 false，让辅助技术知道当前值非法",
        "- 错误容器加 `aria-live` 并设为 polite：内容变化时会朗读，但不打断用户（对比 assertive 会立刻打断）",
        "- 错误容器再加 `aria-atomic=\"true\"`：朗读时播报**整个容器**的内容，而不是只念变动的那几个字",
        "组合起来，屏幕阅读器用户能听到「Please select a customer」，而不仅是看到红字。",
      ],
      code:
        "// app/ui/invoices/create-form.tsx —— 把客户下拉框换成这段（两处加法：select 上加 aria-*，它下面新增错误容器）\n// 前置：本文件顶部需有 import { createInvoice, State } from '@/app/lib/actions';，\n//      组件内需有 const initialState: State = { message: null, errors: {} };\n<select\n  id=\"customer\"\n  name=\"customerId\"\n  className=\"peer block w-full cursor-pointer rounded-md border border-gray-200 py-2 pl-10 text-sm outline-2 placeholder:text-gray-500\"\n  defaultValue=\"\"\n  aria-describedby=\"customer-error\"\n  aria-invalid={state.errors?.customerId ? 'true' : 'false'}\n>\n  {/* options 保持原样 */}\n</select>\n\n// 紧跟在上面 </div>（图标所在的那个 div）之后、外层 </div> 之前，新增错误容器：\n<div id=\"customer-error\" aria-live=\"polite\" aria-atomic=\"true\">\n  {state.errors?.customerId &&\n    state.errors.customerId.map((error: string) => (\n      <p className=\"mt-2 text-sm text-red-500\" key={error}>\n        {error}\n      </p>\n    ))}\n</div>",
      check: "用 `Tab` 走到下拉框时能听到/看到它被标记为无效；错误出现时 `aria-live` 区域会播报。",
      pitfalls: [
        "报 `Property 'customerId' does not exist on type '{}'` → 是 `initialState` 没标 `: State`（见本章第 3 个知识点），不是这两行写错了。",
        "`aria-describedby` 的值是元素的 `id`（不是类名），写错就关联不上。",
        "只把边框变红、不给文字错误，屏幕阅读器用户什么都感知不到。",
      ],
    },
    {
      title: "练习：给其余字段补齐错误提示，并跑一次 lint",
      why: "把模式练熟，另外让工具帮你查出遗漏的无障碍问题。",
      explain: [
        "照 `customerId` 的写法，给 `amount` 与 `status` 也加错误显示与 `aria-describedby`（错误 id 用 `amount-error`、`status-error`）。",
        "然后用 ESLint 自检。⚠️ **Next 16 已移除 `next lint`**（官方课程里那句 `npm run lint` 是旧版本的），本项目也还没配 lint —— 先按三步把它建起来：",
        "- 装依赖：`npm install -D eslint eslint-config-next`",
        "- 在项目根目录新建 `eslint.config.mjs`（Next 的 flat config，见下面代码）",
        "- 在 `package.json` 的 `scripts` 里加一行：键写 `lint`、值写 `eslint`",
        "之后就能跑 `npm run lint`。注意：`eslint-config-next` 只**开启了 6 条** `jsx-a11y` 规则 —— `alt-text`（图片缺 `alt`）+ 5 条 ARIA 合法性检查（`aria-props`、`aria-proptypes`、`aria-unsupported-elements`、`role-has-required-aria-props`、`role-supports-aria-props`）。像「可点击元素不可聚焦」（`click-events-have-key-events`）、「表单控件缺关联 label」这类规则**并没有开启**，所以别指望它替你查出所有无障碍问题。",
        "⚠️ 如果一条无障碍提示都没有，通常是**确实没有违规**（本项目所有 `<Image>` 都带了 `alt`），而不是「没扫到」。想确认它真的在工作：临时把某个 `<Image>` 的 `alt` 删掉再跑一次，会立刻出现 `jsx-a11y/alt-text` 警告，看完记得改回来。",
        "另外，`npm run lint` 的输出里还会有一堆与无障碍**无关**的提示（未使用变量、`react/display-name`、`react-hooks/set-state-in-effect` 等），别混淆 —— 只看以 `jsx-a11y/` 开头的行。",
        "有精力把同样模式套到 `app/ui/invoices/edit-form.tsx` —— 换个地方也能落地才是真学会。",
      ],
      code:
        "// ① package.json —— 在 scripts 里加一行（JSON 里键值要用双引号）：\n//   \"lint\": \"eslint\"\n\n// ② eslint.config.mjs —— 在项目根目录新建这个文件（Next 16 的 flat config）\nimport { defineConfig, globalIgnores } from 'eslint/config';\nimport nextVitals from 'eslint-config-next/core-web-vitals';\nimport nextTs from 'eslint-config-next/typescript';\n\nexport default defineConfig([\n  ...nextVitals,\n  ...nextTs,\n  globalIgnores(['.next/**', 'out/**', 'build/**', 'next-env.d.ts']),\n]);\n\n// ③ 依次执行：\n// npm install -D eslint eslint-config-next\n// npm run lint\n\n// 说明：eslint-config-next 只开启 6 条 jsx-a11y 规则（alt-text + 5 条 ARIA 合法性检查），\n//      所以没有 a11y 输出通常代表「确实没违规」，不代表没生效。\n// 想启用完整规则集：npm install -D eslint-plugin-jsx-a11y，\n//      并在上面 import jsxA11y from 'eslint-plugin-jsx-a11y' 后加入 ...jsxA11y.flatConfigs.recommended",
      check: "三个字段都能显示各自的错误；`npm run lint` 里没有无障碍相关报错。",
      pitfalls: [
        "⚠️ **别以为 a11y 没提示就是没生效**：Next 默认只开 6 条 `jsx-a11y` 规则，只要项目里没有「图片缺 `alt`」和「ARIA 属性写错」这两类问题，它就不会输出任何无障碍内容。",
        "想启用**完整**的无障碍规则集：`npm install -D eslint-plugin-jsx-a11y`，在 `eslint.config.mjs` 里引入并加上 `jsxA11y.flatConfigs.recommended`（Next 默认那 6 条只是它的一个小子集）。",
        "⚠️ **TypeScript 版本坑**：若项目装的是 **TS 7.0**，`eslint` 会直接报 `typescript-eslint does not support TS 7.0`（`typescript-eslint` 目前只支持到 TS 6）。项目里 TS 版本过高时，先降一档：`npm install -D typescript@6`，再跑 `npm run lint`。",
        "`eslint-config-next`（base 与 `/typescript` 都一样）内部依赖 `typescript-eslint`，所以只去掉 `/typescript` 那条并不会绕开这个报错。",
      ],
    },
    {
      title: "动手验证：亲手听一遍屏幕阅读器",
      why: "写了 `aria-*` 却没听过它读出来，等于没验证 —— 只有真读一遍才知道关联接没接上。",
      explain: [
        "验证分三层，从零成本到最接近真实用户：",
        "- **键盘走查**（零安装）：只用 `Tab` / `Shift + Tab` 走一遍，看焦点顺序是否合理、聚焦样式是否可见。能查出「键盘用户到不了」，但查不出「念出来的内容对不对」",
        "- **DevTools 无障碍面板**（零安装）：右键 → 检查 → Elements 面板里的「无障碍 / Accessibility」页签，看「计算后的属性 / Computed Properties」中的 **Name / Role / Description** —— 你加的 `aria-describedby` 内容就出现在 **Description** 里。这是确认「关联有没有接上」最快的方法（它只是**静态快照**，看不到 `aria-live` 的播报）",
        "- DevTools 里选不中元素时，可以用 Elements 面板右上角的 `Switch to Accessibility Tree view` 直接按**无障碍节点**浏览（图标找不到就先在无障碍页签里勾 `Enable full-page accessibility tree`，再点 `Reload DevTools`）",
        "- **真实屏幕阅读器**（最有用）：Windows 自带**讲述人 Narrator**，`Win + Ctrl + Enter` 开关；更推荐免费的 **NVDA**（开源，Windows 10/11，官网 `nvaccess.org`）",
        "NVDA 里对开发者最有用的是**语音查看器**：`工具 / Tools` → `语音查看器 / Speech Viewer`，它把念出的内容以文字显示在一个小窗口里 —— 视力正常的人不用靠耳朵硬听，直接读文字就能验证。",
        "NVDA 够用的几个操作：",
        "- 启动 `Ctrl + Alt + N`；退出 `NVDA + Q`；`Ctrl` 立刻停止朗读",
        "- `Tab` / `Shift + Tab`：在可聚焦元素间移动（表单控件、链接、按钮）",
        "- `NVDA + 空格`：切换「浏览模式 / 焦点模式」（在输入框里打不出字时，多半是停在浏览模式）",
        "- `NVDA + 下箭头`：从当前位置连续朗读；`NVDA + F7`：元素列表（一次列出所有标题 / 链接 / 表单字段）",
        "- 单键跳转（仅浏览模式）：`H` 标题、`F` 表单字段、`B` 按钮、`K` 链接、`R` 地标区域",
        "放在本章的表单上，你应该听到两类内容：**①** `Tab` 走到客户下拉框时，念出「Choose customer, 组合框, Please select a customer, 无效输入」—— 分别是 `label`、你加的 `aria-describedby` 内容、以及 `aria-invalid` 状态；**②** 提交后**焦点不用移动**，`aria-live` 区域里的错误会被**自动播报**出来（「Missing Fields. Failed to Create Invoice.」「Please select an invoice status.」）。",
        "⚠️ 安装 NVDA 时把「用大小写锁定键（CapsLock）作为 NVDA 键」勾上（笔记本没有独立 `Insert` 键）；朗读速度先调到 30–40%，熟练后再加快，否则听不清。",
      ],
      code:
        "// 安装：访问 nvaccess.org 下载 NVDA（免费开源，需 64 位 Windows 10/11）\n\n// 启动 / 停止\nCtrl + Alt + N        // 启动或重启 NVDA\nNVDA + Q              // 退出 NVDA（NVDA 键 = Insert，或勾选后的 CapsLock）\nCtrl                  // 立刻停止朗读\n\n// 导航与朗读\nTab / Shift + Tab     // 下一个 / 上一个可聚焦元素\nNVDA + 空格           // 切换 浏览模式 / 焦点模式\nNVDA + 下箭头         // 从当前位置连续朗读\nNVDA + F7             // 元素列表（标题 / 链接 / 表单字段）\nH  F  B  K  R         // 标题 / 表单字段 / 按钮 / 链接 / 地标（仅浏览模式）\n\n// 工具 / Tools → 语音查看器 / Speech Viewer\n// 把念出的内容以文字显示在窗口里 —— 验证无障碍最直观的方式\n\n// 不想额外装软件时：Windows 自带讲述人\nWin + Ctrl + Enter    // 开关讲述人 Narrator",
      check: "在 NVDA 的语音查看器里看到：聚焦下拉框时会读出 `aria-describedby` 的内容；提交后不移动焦点也能听到错误被播报。",
      pitfalls: [
        "**DevTools 的「计算后的属性」看着一片空白**，通常是三个原因：① 选错了元素 —— 必须选中 `<select>` **本体**（选中 `<label>`、外层 `<div>` 或图标，它们在无障碍树里是 generic / ignored，什么都不显示）；② 「ARIA 属性」「计算后的属性」是**折叠**分组，要先点开，且页签常藏在 Styles 右边的 `»`（更多标签）里；③ **页面当前没有错误，错误容器是空的 → Description 本来就是空的** —— 先用 `Tab` 走到下拉框、提交一次空表单，再回来看，才会出现「Please select a customer」。第 ③ 点最容易让人误判成「没生效」。",
        "DevTools 无障碍面板能显示 `aria-live` 属性，但**看不到播报效果** —— 播报是朗读事件，必须用真屏幕阅读器验证。",
        "NVDA 在输入框里打字需先进入焦点模式（`NVDA + 空格`），否则字母会被当成导航快捷键。",
        "别只看「有没有报错」，要听「顺序和内容是否合理」：自动扫描工具通常只能查出约三成问题。",
      ],
      note: "测试时**别用鼠标** —— 屏幕阅读器用户没有鼠标；一旦点击页面，测试就不真实了。全程键盘操作，卡住时按 `Ctrl` 停止朗读、`Ctrl + Home` 回到页首。",
    },
    {
      title: "提交失败后表单被清空？React 19 的表单重置行为",
      why: "校验失败时要保留用户已填的内容，否则用户得从头再填一遍。",
      explain: [
        "现象：某个字段没填就提交 —— 错误提示出来了，但**输入框全被清空**。这既不是你的 bug，也不是「页面刷新了」。",
        "原因：React 19 里，只要 `<form action={...}>` 的 action **正常返回**（返回校验错误也算正常返回，只要没抛异常），React 就会**重置表单里所有非受控控件**，为的是与原生表单提交行为保持一致。校验通过时你察觉不到（紧接着就 `redirect` 走了），只有在校验失败、需要保留输入时才暴露出来。",
        "注意这个关键区别：被重置的只有 **DOM 上的表单值**，`useActionState` 的 `state` **不会**被重置 —— 这正是「错误提示还在、输入却没了」的由来。",
        "先确认到底是哪一种：打开 DevTools 的 Console。**Console 被清空、地址栏出现加载进度 → 那是真的整页刷新**（说明表单没走 action，或有别的错误）；**Console 内容还在、只是输入框空了 → 就是下面这个重置行为**。",
        "修法（可选，官方课程没有处理这一点）：把用户填的原始值一起 `return` 回客户端，再用 `defaultValue` / `defaultChecked` 回填。三步：",
        "- ① `State` 里加一个 `fields` 字段，存用户的原始输入",
        "- ② action 的失败分支把原始值一并返回（`fields: raw`）",
        "- ③ 表单控件改成 `defaultValue={state.fields?.xxx ?? ''}`；单选改成 `defaultChecked={state.fields?.status === 'pending'}`",
        "⚠️ `<select>` 是社区已知的例外：`defaultValue` 主要在**挂载时**生效，重置后可能仍显示为空。要它稳定回填，就把这个下拉框**单独做成受控**（`useState` + `value` / `onChange`）—— 受控控件不属于「非受控控件」，**不受表单重置影响**。",
      ],
      code:
        "// ① app/lib/actions.ts —— State 里加 fields（存用户原始输入）\nexport type State = {\n  errors?: {\n    customerId?: string[];\n    amount?: string[];\n    status?: string[];\n  };\n  message?: string | null;\n  fields?: {\n    customerId?: string;\n    amount?: string;\n    status?: string;\n  };\n};\n\n// ② app/lib/actions.ts —— 先取出原始值，失败时一并 return\nexport async function createInvoice(prevState: State, formData: FormData) {\n  const raw = {\n    customerId: formData.get('customerId')?.toString() ?? '',\n    amount: formData.get('amount')?.toString() ?? '',\n    status: formData.get('status')?.toString() ?? '',\n  };\n\n  const validatedFields = CreateInvoice.safeParse({\n    customerId: raw.customerId,\n    amount: raw.amount,\n    status: raw.status,\n  });\n\n  if (!validatedFields.success) {\n    return {\n      errors: validatedFields.error.flatten().fieldErrors,\n      message: 'Missing Fields. Failed to Create Invoice.',\n      fields: raw,   // ← 新增：把原始输入带回客户端\n    };\n  }\n\n  // 成功分支保持原样：写库 → revalidatePath → redirect\n}\n\n// ③ app/ui/invoices/create-form.tsx —— 用返回值做默认值\n<select name=\"customerId\" defaultValue={state.fields?.customerId ?? ''}>\n\n<input name=\"amount\" defaultValue={state.fields?.amount ?? ''} />\n\n<input\n  type=\"radio\"\n  name=\"status\"\n  value=\"pending\"\n  defaultChecked={state.fields?.status === 'pending'}\n/>\n\n<input\n  type=\"radio\"\n  name=\"status\"\n  value=\"paid\"\n  defaultChecked={state.fields?.status === 'paid'}\n/>\n\n// ④ 若 <select> 仍不回填，把它单独做成受控（受控控件不会被表单重置影响）：\n//    记得在文件顶部 import { useState } from 'react';\nconst [customerId, setCustomerId] = useState('');\n\n<select\n  name=\"customerId\"\n  value={customerId}\n  onChange={(e) => setCustomerId(e.target.value)}\n>",
      check: "故意漏填一项提交：错误提示出现的同时，已经填好的其它字段仍然保留原值。",
      pitfalls: [
        "别把它当成「页面刷新」去查：重点看 Console 有没有被清空、地址栏有没有加载进度。",
        "只有**非受控**控件会被重置；受控控件（带 `value` + `onChange`）不受影响。",
        "`state` 不会被重置，所以不能靠「错误是否消失」判断有没有发生重置。",
      ],
      note: "这是官方课程**没有覆盖**的真实行为。你也可以选择不做保留（表单页面切走得快，成本有限），但要知道它的存在，否则将来遇到会以为是玄学。",
    },
  ],
  tips: [
    "本章模式：**服务端 zod `safeParse` 返回错误 → `useActionState` 接管状态 → 界面用 `aria-` 系列属性把错误讲清楚**。",
    "无障碍不是额外负担：语义化 HTML + 明确反馈，既帮助辅助技术用户，也让所有用户出错时更清楚发生了什么。",
  ],
};
