import type { Chapter } from "./types";

export const chapter14: Chapter = {
  num: 14,
  slug: "adding-authentication",
  title: "Adding Authentication",
  titleZh: "添加身份认证",
  officialUrl:
    "https://nextjs.org/learn/dashboard-app/adding-authentication",
  summary:
    "⚠️ 开始前：本章需要先装依赖 `npm install next-auth@beta`（**`@beta` 不能省**，不加会装到 v4，API 完全不同）。用 NextAuth.js（Auth.js）配置 Credentials 登录，做登录页、登录表单与路由保护，最后加上登出。**本地默认测试账号：`user@nextmail.com` / 密码 `123456`**（第 6 章种子数据自带，详见「配置 Auth」知识点）。",
  goals: [
    "理解认证（authentication）要解决的问题，以及为什么要用成熟库",
    "会用 Auth.js / NextAuth 配置 Credentials provider，并用 bcrypt 校验密码",
    "会用 `useActionState` 处理登录错误与 pending 状态",
    "会用 Proxy（旧称 middleware）保护 `/dashboard`",
    "会实现登出",
  ],
  points: [
    {
      title: "认证要做什么，为什么不自研",
      why: "认证涉及会话、Cookie、加密、CSRF 等一堆易错细节，自研几乎必然出漏洞。",
      explain: [
        "**认证（Authentication）** 回答「你是谁」，**授权（Authorization）** 回答「你能做什么」。本章只做认证：加登录页，未登录不能进 `/dashboard`。",
        "课程用 **NextAuth.js（现名 Auth.js）** + **Credentials provider**（邮箱 + 密码）+ **bcrypt**（比对哈希密码）。密码永远以哈希形式存在库里（第 6 章播种时已处理），登录时只做 `bcrypt.compare`。",
        "不自研的理由：自己写会话意味着要处理签名 Cookie、过期、刷新、CSRF、时序攻击等。另外本课程**还没做授权**（角色与权限）—— 那是后续可以自己加的方向。",
      ],
      check: "能区分「认证」与「授权」，并说出课程为什么选 Credentials provider。",
    },
    {
      title: "创建登录页",
      why: "先给用户一个入口，后面的配置才有地方验证。",
      explain: [
        "新建 `app/login/page.tsx`，渲染课程准备好的 `<LoginForm />`（`app/ui/login-form.tsx`）。",
        "要用 **`<Suspense>`** 包起来 —— 登录表单会读 URL 里的 `callbackUrl`（登录后回跳地址），属于运行时参数，会触发客户端渲染。与第 10 章「用 Suspense 包住读 URL 参数的组件」同理。",
      ],
      note: "官方这一步的示例代码里**没有** metadata —— 给登录页加标题不在本章要求内。如果你想让 `/login` 也有自己的标题，可以照第 15 章的写法在这个文件顶部加 `import type { Metadata } from 'next';` 和 `export const metadata: Metadata = { title: 'Login' };`。这是可选的，不影响本章任何步骤。",
      code:
        "// app/login/page.tsx\nimport AcmeLogo from '@/app/ui/acme-logo';\nimport LoginForm from '@/app/ui/login-form';\nimport { Suspense } from 'react';\n\nexport default function LoginPage() {\n  return (\n    <main className=\"flex items-center justify-center md:h-screen\">\n      <div className=\"relative mx-auto flex w-full max-w-[400px] flex-col space-y-2.5 p-4 md:-mt-32\">\n        <div className=\"flex h-20 w-full items-end rounded-lg bg-blue-500 p-3 md:h-36\">\n          <div className=\"w-32 text-white md:w-36\">\n            <AcmeLogo />\n          </div>\n        </div>\n        <Suspense>\n          <LoginForm />\n        </Suspense>\n      </div>\n    </main>\n  );\n}",
      check: "访问 `/login` 能看到登录表单页面正常渲染（本步只验证「页面能打开」，先不用管提交行为）。",
    },
    {
      title: "配置 Auth：为什么把配置拆成两个文件",
      why: "本章最容易「照抄却不懂」的地方，理解拆分原因就不会写错。",
      explain: [
        "⚠️ **先装依赖（官方本章的第一步就是它）**：在项目根目录执行 `npm install next-auth@beta`。**`@beta` 不能省** —— 不加它会装到 v4，而 v4 的 API 完全不同（`authOptions` + `getServerSession` + `app/api/auth/[...nextauth]/route.ts`），照本章代码写会一路报错。装完可以看 `package.json` 确认是 `^5.x`。",
        "`bcrypt` **不用再装** —— 第 6 章播种密码时就装了（现在已经是依赖之一）。",
        "两个文件：",
        "- `auth.config.ts`：**与运行环境无关的配置**（`pages`、`providers` 空数组、`callbacks`）",
        "- `auth.ts`：`NextAuth({ ...authConfig, providers: [Credentials({ authorize })] })`，导出 `handlers`、`auth`、`signIn`、`signOut`",
        "两个文件都建在**项目根目录**（不是 `app/` 里）。",
        "为什么拆？路由保护（Proxy / 旧称 middleware）运行在**受限运行时**，不能引入依赖 Node 专有 API 的模块。`bcrypt` 依赖 Node 加密能力，而 `auth.config.ts` 不含它，所以能被 Proxy 安全引用；完整的 `auth.ts`（含 bcrypt）只在服务端用。",
        "两份配置是**子集与全集**的关系：`auth.config.ts` 是「Proxy 能安全加载的那一半」（`pages` + `callbacks.authorized` + `providers: []` 占位），`auth.ts` 用 `{ ...authConfig, providers: [...] }` 把子集展开、再补上需要 Node 的部分。",
        "⚠️ **版本变化（Next 16）**：上面「受限运行时」的理由来自 Next 14/15 —— 那时 `middleware.ts` 跑在 Edge 运行时，确实没有 Node API。**Next 16 把 middleware 改名为 `proxy.ts`，并且它也默认跑在 Node.js 运行时**，所以严格说现在让 proxy 直接引用完整的 `auth.ts` 也能工作。课程仍然拆成两份：一是照官方来，二是这样 proxy 只加载它真正需要的轻量配置（更清晰、启动更省）。知道有这层变化即可，写法不用改。",
        "所以 `providers: []` 这个**空数组不是随便写的**：它是配置类型要求的字段，先用空数组占位（满足类型），到 `auth.ts` 才被真正的 `Credentials(...)` 替换。这样「要连数据库、要跑 `bcrypt`」的 `authorize` 就永远进不了 Proxy 的构建产物。",
        "`authorize` 是核心，顺序是固定的：**先用 zod 校验 `credentials`** → 通过后取出 `email` / `password` → 用 `getUser(email)` 查库（查不到 `return null`）→ `bcrypt.compare(password, user.password)` 比对哈希 → 匹配则返回用户对象。",
        "⚠️ **本项目的适配点（照抄官方会踩）**：官方回调里 `authorized` 的第二个分支是「**只要已登录、访问任何非 `/dashboard` 的路径，就送回 `/dashboard`**」。官方 Acme 应用里非 dashboard 页面只有 `/` 和 `/login`，所以没影响；但**这个工作台的 `/` 和 `/chapters/*` 是你要天天看的页面**，照抄的结果就是「登录成功后，一打开章节页就被弹回 dashboard」。所以要把重定向**收窄到 `/login`**（见下面代码里的注释）。",
        "⚠️ **为什么「先 zod 校验」不能省**：`credentials` 的类型是 `Partial<Record<string, unknown>>`，字段都是 `unknown`。直接把 `credentials.email` 传进 `sql` 模板，会因为「`unknown` 不能作为查询参数」报 `No overload matches this call … not assignable to parameter of type 'never'`（`ts(2769)`）。**校验通过后 `parsedCredentials.data` 里的 `email` / `password` 才是 `string`**，才能安全地交给查询和 `bcrypt.compare`。",
        "`getUser` 单独抽成一个函数，是为了给它标注入参 `email: string`、返回 `Promise<User | undefined>`，并用 `sql<User[]>` 指定查询结果类型 —— 这也是本项目 `app/lib/data.ts` 里统一的写法。",
        "还要配 `AUTH_SECRET`（用于签名会话令牌）：`npx auth secret` 生成并写入 `.env` —— 这个命令由 next-auth v5 自带，所以要在**装完依赖之后**再跑。",
      ],
      code:
        "// ① 先装依赖（在项目根目录执行）—— @beta 不能省\n// npm install next-auth@beta\n// bcrypt 第 6 章已装，不用重复安装\n\n// ② 生成 AUTH_SECRET（会自动写入 .env.local；若无此命令可手动生成）\n// npx auth secret\n// 备选：node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\"\n// 然后把得到的字符串以 AUTH_SECRET=<值> 的形式加进 .env\n\n// ③ 下面两个文件都建在**项目根目录**\n// auth.config.ts\nimport type { NextAuthConfig } from 'next-auth';\n\nexport const authConfig = {\n  pages: { signIn: '/login' },\n  providers: [], // 在 auth.ts 里补上\n  callbacks: {\n    authorized({ auth, request: { nextUrl } }) {\n      const isLoggedIn = !!auth?.user;\n      const isOnDashboard = nextUrl.pathname.startsWith('/dashboard');\n      if (isOnDashboard) {\n        if (isLoggedIn) return true;\n        return false; // 未登录 → 重定向到 pages.signIn（/login）\n      }\n      // 已登录去访问 /login 时才送回 dashboard。\n      // ⚠️ 官方写法是「其余任何路径都送回 dashboard」，但本项目还有 / 与 /chapters/* 这些页面要能看，\n      //    所以把重定向收窄到 /login（否则登录后一访问章节页就被弹走）。\n      if (isLoggedIn && nextUrl.pathname === '/login') {\n        return Response.redirect(new URL('/dashboard', nextUrl));\n      }\n      return true;\n    },\n  },\n} satisfies NextAuthConfig;\n\n// auth.ts\nimport NextAuth from 'next-auth';\nimport Credentials from 'next-auth/providers/credentials';\nimport { authConfig } from './auth.config';\nimport { z } from 'zod';\nimport type { User } from '@/app/lib/definitions';\nimport bcrypt from 'bcrypt';\nimport postgres from 'postgres';\n\nconst sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });\n\nasync function getUser(email: string): Promise<User | undefined> {\n  try {\n    const user = await sql<User[]>`SELECT * FROM users WHERE email=${email}`;\n    return user[0];\n  } catch (error) {\n    console.error('Failed to fetch user:', error);\n    throw new Error('Failed to fetch user.');\n  }\n}\n\nexport const { auth, signIn, signOut } = NextAuth({\n  ...authConfig,\n  providers: [\n    Credentials({\n      async authorize(credentials) {\n        // 先校验：这样 email / password 才是 string，能安全传给 sql 与 bcrypt\n        const parsedCredentials = z\n          .object({ email: z.string().email(), password: z.string().min(6) })\n          .safeParse(credentials);\n\n        if (parsedCredentials.success) {\n          const { email, password } = parsedCredentials.data;\n          const user = await getUser(email);\n          if (!user) return null;\n          const passwordsMatch = await bcrypt.compare(password, user.password);\n          if (passwordsMatch) return user;\n        }\n\n        console.log('Invalid credentials');\n        return null;\n      },\n    }),\n  ],\n});",
      check: "依赖已装（`package.json` 里是 `next-auth` 的 `^5.x`）；两个文件建好、`AUTH_SECRET` 写进 `.env`；`auth.ts` 没有任何类型错误，项目能正常启动。",
      pitfalls: [
        "⚠️ **登录后连 `/`、`/chapters/*` 都被弹到 `/dashboard`**：这是照抄官方那份「已登录就送回 dashboard」的回调造成的。本项目的学习页面都在 `/dashboard` 之外，所以要把它收窄成「只在访问 `/login` 时送回 dashboard」（见上方代码与讲解）。",
        "⚠️ 装成 `next-auth`（不带 `@beta`）会拿到 v4 —— API 完全不同（`authOptions` / `getServerSession` / `[...nextauth].ts`），本章代码会全线报错。装完用 `npm ls next-auth` 确认版本是 `5.x`。",
        "跳过 zod 校验、直接写 `credentials.email` → 报 `ts(2769)`（`unknown` 不能作为查询参数）。这不是类型系统太严，而是提醒你「先校验再使用」。",
        "在 `auth.config.ts` 里 import `bcrypt`，会让路由保护那一步报运行时错误 —— 这正是要拆文件的原因。",
        "忘记配置 `AUTH_SECRET`：会话无法签名，登录行为异常。",
        "**登录用的账号密码**：`user@nextmail.com` / `123456`。它就写在第 6 章的种子数据 `app/lib/placeholder-data.ts` 的 `users` 数组里（`app/seed/route.ts` 播种时用 `bcrypt.hash(user.password, 10)` 哈希后才入库，所以库里存的是哈希、登录时才用 `bcrypt.compare` 比对）。⚠️ 前提是数据库**播种过** —— 若这个账号报 `Invalid credentials.`，先访问一次 `/seed`（`ON CONFLICT (id) DO NOTHING`，重复跑安全）。想换账号：改那个文件里的 `email` / `password` 再访问 `/seed`；注意去重是按 `id` 的，只改密码不改 `id` 不会更新，要连 `id` 一起换。",
      ],
      note: "官方示例的 `authorize` 是直接 `return user`（对象里还带着 `password` 字段）。如果你想更保险，可以在返回前把 `password` 解构掉：`const { password, ...userWithoutPassword } = user; return userWithoutPassword;` —— 可选项，不影响本章后续步骤。",
    },
    {
      title: "写 authenticate：登录用的 Server Action",
      why: "登录也是一次写操作，用 Server Action 正好延续第 11 章的模式。",
      explain: [
        "在 `app/lib/actions.ts` 新增 `authenticate(prevState, formData)`：取 email / password，然后 `await signIn('credentials', { ...credentials, redirectTo: '/dashboard' })`（课程里也会用到 `callbackUrl`）。",
        "失败处理：`signIn` 在凭据错误时抛 `AuthError`。外层 `try/catch`，`catch` 里 `if (error instanceof AuthError)` 就 `return 'Invalid credentials.'`，其他未知错误 `return 'Something went wrong.'`。",
        "注意 `authenticate` **不用 zod**（课程选择），直接把凭据交给 Auth.js 的 `authorize` 校验 —— 校验逻辑集中在 `auth.ts`。",
      ],
      code:
        "// app/lib/actions.ts —— 在已有内容下面「追加」这个函数\n//（文件里已经有 'use server' 与 createInvoice / updateInvoice / deleteInvoice，都不动）\n// 只在顶部补这两个 import：\nimport { signIn } from '@/auth';\nimport { AuthError } from 'next-auth';\n\nexport async function authenticate(prevState: string | undefined, formData: FormData) {\n  try {\n    await signIn('credentials', formData);\n  } catch (error) {\n    if (error instanceof AuthError) {\n      switch (error.type) {\n        case 'CredentialsSignin':\n          return 'Invalid credentials.';\n        default:\n          return 'Something went wrong.';\n      }\n    }\n    throw error; // 注意：redirect 也靠抛错实现，必须把非 AuthError 重新抛出\n  }\n}",
      check: "用测试账号 `user@nextmail.com` / `123456` 试提交：`tsc` 无类型错误；用**正确**密码提交后页面会跳转/刷新（此时还没传 `redirectTo`，所以不会进 `/dashboard`），能看到跳转就说明 `signIn` 成功了；用**错误**密码提交时界面暂时**不会显示任何提示** —— 错误要等下一步才被渲染出来（想确认服务端确实拒绝了，可看终端里 `auth.ts` 那行 `console.log('Invalid credentials')`）。",
      pitfalls: [
        "在 catch 里把所有错误都 `return` 成字符串，会导致**登录成功后不跳转**（成功跳转也走抛错路径）—— 和上一章 `redirect` 的坑同源。",
      ],
    },
    {
      title: "登录表单：useActionState + 登录后回跳",
      why: "把错误显示出来、把「你从哪来」记住，登录体验才完整。",
      explain: [
        "⚠️ **先分清两个名字，这是本节最容易错的地方**：",
        "- **URL 查询参数**叫 `callbackUrl`，**由 Auth.js 在拦截时自动附加**（不是你写的 —— 你只决定跳到哪个页面，即 `auth.config.ts` 里的 `pages.signIn`）。它的值是**完整的绝对 URL 且做了编码**，例如未登录访问 `/dashboard/invoices?page=2` 会得到 `/login?callbackUrl=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Finvoices%3Fpage%3D2` —— 连原来的查询串都保留，所以登录后能回到带分页/搜索状态的页面。你只需用 `searchParams.get('callbackUrl')` 把它读出来（starter 里已经写好这一行）",
        "- **表单隐藏字段**必须叫 `redirectTo` —— `authenticate` 里是 `signIn('credentials', formData)`，Auth.js 会按「选项名」从 FormData 里取值；字段名写错它就不认，登录后不会回到原目标页。（`callbackUrl` 是旧版的选项名，Auth.js v5 已废弃并改名为 `redirectTo`）",
        "starter 自带的 `app/ui/login-form.tsx` **已经写好了** `'use client'`、几个 import，以及组件体里的三行（`searchParams` / `callbackUrl` / `useActionState`）。所以你只需改**三处**：",
        "- ① 在 email / password 那组输入的收尾 `</div>` 之后、`<Button>` 之前，插入一个隐藏字段：`name` 写 `redirectTo`、`value` 写 `{callbackUrl}`（完整写法见下面代码的注释 ①）",
        "- ② 给 `<Button>` 加上 `aria-disabled={isPending}` —— starter 的 `Button` 样式里写了 `aria-disabled:` 变体，用这个属性才看得到置灰效果",
        "- ③ 把那个空占位（`{/* Add form errors here */}`）补成错误区：外层 div 加 `aria-live` 与 `aria-atomic`，里面渲染 `ExclamationCircleIcon` 与 `errorMessage` —— 与第 13 章的错误显示是同一套思路",
        "⚠️ **这一步还测不了「未登录被弹到登录页」** —— 那需要请求级拦截，也就是**下一个知识点的 `proxy.ts`**。现在没人拦你，直接访问 `/dashboard/invoices` 会照常打开，这是正常的。",
        "想**提前**看「登录后回跳」的效果：手动访问 `/login?callbackUrl=/dashboard/invoices` 再登录 —— 表单会把这个参数塞进隐藏字段，Auth.js 读 `redirectTo` 就会跳回 invoices 页。（等下一步建好 `proxy.ts`，这个参数由拦截逻辑自动帮你带上。）",
        "这套机制**可以调**，按上下半程分开看：",
        "- **上半程**（谁附加 `callbackUrl`）：默认是 Auth.js 干的。想自己控制，就别在 `authorized` 里 `return false`，而是直接 `return Response.redirect(new URL('/login', nextUrl))` —— 这样 Auth.js 不再插手，带不带参数、参数叫什么全由你写",
        "- **下半程**（登录成功后去哪）：完全由你决定 —— 改隐藏字段的值即可；不想自动跳转就用 `signIn('credentials', { redirect: false })`，回到客户端由你自己 `router.push(...)`",
        "- 想**统一改写/兜底**：加一个 `redirect` 回调（与 `authorized` **并列**写在同一个 `callbacks` 里，别把 `authorized` 删了）",
      ],
      code:
        "// app/ui/login-form.tsx —— 这一步做完后的完整文件（starter 版本上改了 ①②③ 三处）\n'use client';\n\nimport { lusitana } from '@/app/ui/fonts';\nimport {\n  AtSymbolIcon,\n  KeyIcon,\n  ExclamationCircleIcon,\n} from '@heroicons/react/24/outline';\nimport { ArrowRightIcon } from '@heroicons/react/20/solid';\nimport { Button } from './button';\nimport { useActionState } from 'react';\nimport { useSearchParams } from 'next/navigation';\nimport { authenticate } from '@/app/lib/actions';\n\nexport default function LoginForm() {\n  const searchParams = useSearchParams();\n  const callbackUrl = searchParams.get('callbackUrl') || '/dashboard';\n  const [errorMessage, formAction, isPending] = useActionState(\n    authenticate,\n    undefined,\n  );\n\n  return (\n    <form action={formAction} className=\"space-y-3\">\n      <div className=\"flex-1 rounded-lg bg-gray-50 px-6 pb-4 pt-8\">\n        <h1 className={`${lusitana.className} mb-3 text-2xl`}>\n          Please log in to continue.\n        </h1>\n        <div className=\"w-full\">\n          <div>\n            <label\n              className=\"mb-3 mt-5 block text-xs font-medium text-gray-900\"\n              htmlFor=\"email\"\n            >\n              Email\n            </label>\n            <div className=\"relative\">\n              <input\n                className=\"peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500\"\n                id=\"email\"\n                type=\"email\"\n                name=\"email\"\n                placeholder=\"Enter your email address\"\n                required\n              />\n              <AtSymbolIcon className=\"pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900\" />\n            </div>\n          </div>\n          <div className=\"mt-4\">\n            <label\n              className=\"mb-3 mt-5 block text-xs font-medium text-gray-900\"\n              htmlFor=\"password\"\n            >\n              Password\n            </label>\n            <div className=\"relative\">\n              <input\n                className=\"peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500\"\n                id=\"password\"\n                type=\"password\"\n                name=\"password\"\n                placeholder=\"Enter password\"\n                required\n                minLength={6}\n              />\n              <KeyIcon className=\"pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900\" />\n            </div>\n          </div>\n        </div>\n        {/* ① 新增：告诉 Auth.js 登录后回哪；字段名必须是 redirectTo */}\n        <input type=\"hidden\" name=\"redirectTo\" value={callbackUrl} />\n        {/* ② 改动：Button 加 aria-disabled（它的样式里有 aria-disabled: 变体） */}\n        <Button className=\"mt-4 w-full\" aria-disabled={isPending}>\n          Log in <ArrowRightIcon className=\"ml-auto h-5 w-5 text-gray-50\" />\n        </Button>\n        {/* ③ 改动：把原来的空占位 div 补成带 aria-live 的错误区 */}\n        <div\n          className=\"flex h-8 items-end space-x-1\"\n          aria-live=\"polite\"\n          aria-atomic=\"true\"\n        >\n          {errorMessage && (\n            <>\n              <ExclamationCircleIcon className=\"h-5 w-5 text-red-500\" />\n              <p className=\"text-sm text-red-500\">{errorMessage}</p>\n            </>\n          )}\n        </div>\n      </div>\n    </form>\n  );\n}",
      check: "直接访问 `/login`，用 `user@nextmail.com` + **错误**密码提交能看到 `Invalid credentials.`；用 `123456` 提交能进入 `/dashboard`。（「被弹到登录页」「登录后回跳」要等下一步建好 `proxy.ts` 才完整可测。）",
      pitfalls: [
        "⚠️ **Auth.js 默认只允许「同源」跳转**（`redirect` 回调的默认实现：相对路径或同源 URL 才放行，否则退回 `baseUrl`）—— 所以就算别人改了隐藏字段里的 `redirectTo`，也跳不到外站。**但你自己在 action 里拼接跳转地址**（例如 `redirect(formData.get(...))`）就绕过了这层保护，那种写法必须自己校验，否则是 open redirect 漏洞。",
        "隐藏字段的 `name` 写成 `callbackUrl`：**不会报错**，但 Auth.js 不认这个选项名 —— 登录成功后会跳到它自己的默认页，而不是你原本想去的页面。URL 参数才叫 `callbackUrl`，表单字段叫 `redirectTo`。",
        "别把 `<Button>` 换成原生 `<button>`：starter 的 `Button` 带完整样式（含 `aria-disabled:` 变体、图标间距），换掉会丢样式、也看不到 pending 的置灰效果。",
      ],
    },
    {
      title: "保护路由：用 Proxy（旧称 middleware）",
      why: "认证要在「每个受保护请求」上都拦一道。",
      explain: [
        "⚠️ **这一步不做，前面全部白做**：只要 `proxy.ts` 不存在，就**没有任何请求级拦截** —— 直接访问 `/dashboard/invoices` 会照常渲染（页面自己不会检查登录状态）。「访问 dashboard 没被弹到登录页」= 这个文件还没建。",
        "在**项目根目录**创建 `proxy.ts`（Next.js 16 的新名字，与 `app/` 同级）。内容是 `export default NextAuth(authConfig).auth;` + 一个 matcher 声明要拦截哪些路径。",
        "重定向逻辑不写在这里，而在 `auth.config.ts` 的 **`callbacks.authorized`**（上一步已写好）：判断「是否已登录」与「是否访问 dashboard」，未登录返回 `false`，Auth.js 就重定向到 `pages.signIn` 的 `/login`。",
        "更细的用法：页面里可 `const session = await auth();`，按 `session?.user` 判断是否渲染某些内容（甚至做**基于角色的授权**）。这是「页面级检查」，与 Proxy 的「请求级拦截」互补。",
        "**先想清楚「哪些页面受保护」** —— 本项目其实只有两个区域：",
        "- **练习区（受保护）**：`/dashboard/*` —— 课程练习都在里面，未登录要拦",
        "- **学习区（公开）**：`/`、`/chapters/*` —— 你天天看的知识点与章节页，**不该被登录拦住**；`/api/*`（编辑器探测、路径存在性检查）也属于这类基础设施",
        "两个机制都能表达这件事，选一个即可：",
        "- **回调里判断**（承上一步）：`authorized` 只把 `Response.redirect` 用在 `/login` 上，其余路径 `return true`",
        "- **matcher 收窄**（更结构化的做法，推荐）：让 proxy 只在这些路径上运行 —— `matcher: ['/dashboard/:path*', '/login']`。本项目的路由里**受保护的只有 `/dashboard` 及其子页**（`/dashboard/customers`、`/dashboard/invoices`、`/dashboard/invoices/create`、`/dashboard/invoices/[id]/edit`）；而 `/`（工作台首页）、`/chapters/*`、`/playground`（练习区）、`/api/*`、`/seed` **根本不进 proxy**，从结构上就不会被登录影响（用这个写法时，回调保留官方原版也是正确的）",
      ],
      note: "旧文档与教程里写的是 `middleware.ts` —— Next.js 16 把它改名为 `proxy.ts`，同时运行环境也从 Edge 换成了 **Node.js**（功能不变，只是名字与运行时变了）。按你安装的版本写，别照抄旧教程。",
      code:
        "// proxy.ts（项目根目录，Next.js 16 的写法）\nimport NextAuth from 'next-auth';\nimport { authConfig } from './auth.config';\n\nexport default NextAuth(authConfig).auth;\n\nexport const config = {\n  // 官方那条是「除了 api/静态资源以外全拦」，再在 authorized 里判断放行；\n  // 本项目更推荐「白名单」写法 —— 只拦受保护区，`/`、`/chapters/*`、`/playground` 等根本不进 proxy：\n  matcher: ['/((?!api|_next/static|_next/image|.*\\\\.png$).*)'],\n  // matcher: ['/dashboard/:path*', '/login'],   // ← 推荐（:path* 也匹配 /dashboard 本身）\n};",
      check: "登出状态下直接访问 `/dashboard/invoices`，被重定向到 `/login?callbackUrl=%2Fdashboard%2Finvoices`；在那里用 `user@nextmail.com` / `123456` 登录成功后**自动回到 invoices 页** —— 这才把上一步的隐藏字段一起验证了。",
      pitfalls: [
        "**只建了 `auth.config.ts` / `auth.ts` 不会产生任何拦截** —— 拦截是 `proxy.ts` 负责调起的。访问 `/dashboard` 没被弹到登录页，第一反应就该查这个文件在不在。",
        "文件必须是**项目根目录**的 `proxy.ts`（与 `app/` 同级）；放进 `app/` 或换个名字都不会生效（旧版才叫 `middleware.ts`）。",
        "⚠️ **matcher 只挖「chapters」这个洞，会漏掉 favicon 等非页面资源**：如果选用官方那条负向匹配 + 只补一个 `chapters`（`'/((?!api|_next/static|_next/image|chapters|.*\\.png$).*)'`），那么 `/favicon.ico`、`/robots.txt`、`/`（首页）、`/playground` **仍然会进 proxy**，再碰上官方原版回调，就会出现：",
        "- **`/favicon.ico` 返回 302** → 浏览器拿到的是 `/dashboard` 的 HTML 而不是图标 → **标签页图标不显示**（用 curl 之类不带 cookie 的请求测却是 200，因为未登录走 `return true` 分支，所以「本地 curl 正常、浏览器不生效」）",
        "- 同理，已登录时打开 `/` 或 `/playground` 也会被送到 `/dashboard`",
        "**所以只挖洞不够** —— 至少要两者之一做对：**把回调的 `Response.redirect` 收窄到 `/login`**（推荐，见上一步），或改用**白名单 matcher** `['/dashboard/:path*', '/login']`（推荐做法，除 dashboard 和 login 外一律不进 proxy）。两个都做最稳。",
        "matcher 不写或写漏，Proxy 会连静态资源（`_next/static`、图片）都拦 → 样式/图片被重定向而加载失败。用上面那条负向匹配最省事。",
        "matcher 太宽会把静态资源也拦进去；写得不对可能连登录页都被保护，形成重定向死循环。",
      ],
    },
    {
      title: "加上登出",
      why: "有进有出，认证流程才闭环。",
      explain: [
        "在 `app/ui/dashboard/sidenav.tsx` 里只改两处：**① 顶部 import 区加 `import { signOut } from '@/auth';`**（`PowerIcon` starter 里本来就 import 了，不用再加）；**② 给那个已经存在的 `<form>` 补上 `action`**。",
        "⚠️ **不要新增 `<form>`**：starter 的侧边栏里**已经有一个 `<form>`**，里面包着 PowerIcon 按钮，只是没有 `action`（所以现在点了没反应）—— 本步是给它补 `action`。另外这个文件里**没有 `<nav>`**，容器是那个 `flex grow flex-row…` 的 `div`，别去找 `<nav>`。",
        "`signOut` 从**根目录的 `auth.ts`** 引入（就是上一步里 `NextAuth(...)` 导出的那个），不是从 `next-auth/react` 引。",
        "用**表单 + 内联 Server Action** 而不是 `onClick`：延续第 11 章的渐进增强思路（JS 没加载好也点得动）。内联 Server Action 只能定义在**服务端组件**里 —— `sidenav.tsx` 没有 `'use client'`，正好满足。",
        "`signOut({ redirectTo: '/' })` 里的 `redirectTo` 决定登出后去哪 —— 官方用首页 `/`（本项目首页就是公开的章节清单，落在这里很自然）；想直接回登录页就写 `'/login'`。",
        "⚠️ **`'use server'` 为什么写在函数体里？** 它不是普通字符串，而是**给编译器的指令**（和 `'use client'` 同类），有两种写法：",
        "- 写在**文件第一行** → 该模块**导出的函数全都**是 Server Action（`app/lib/actions.ts` 就是这种，所以它只能导出 async 函数）",
        "- 写在**函数体第一行** → **只把这一个函数**标记成 Server Action（本节用的，叫「内联 Server Action」，适合只用一次的短逻辑）",
        "两种写法编译器都会做同一件事：**把函数源码留在服务端**，客户端只拿到一个「action 引用（id）」；用户触发时浏览器把这个 id POST 回服务端，服务端执行完再返回结果/重定向。所以「这段代码只在服务端跑」就是靠这个不起眼的一行实现的。",
      ],
      code:
        "// app/ui/dashboard/sidenav.tsx —— 本步只改两处：① 顶部 import ② 给已存在的 <form> 补 action\nimport Link from 'next/link';\nimport NavLinks from '@/app/ui/dashboard/nav-links';\nimport AcmeLogo from '@/app/ui/acme-logo';\nimport { PowerIcon } from '@heroicons/react/24/outline';\nimport { signOut } from '@/auth';   // ← ① 新增（PowerIcon 本来就有）\n\nexport default function SideNav() {\n  return (\n    <div className=\"flex h-full flex-col px-3 py-4 md:px-2\">\n      <Link\n        className=\"mb-2 flex h-20 items-end justify-start rounded-md bg-blue-600 p-4 md:h-40\"\n        href=\"/\"\n      >\n        <div className=\"w-32 text-white md:w-40\">\n          <AcmeLogo />\n        </div>\n      </Link>\n      <div className=\"flex grow flex-row justify-between space-x-2 md:flex-col md:space-x-0 md:space-y-2\">\n        <NavLinks />\n        <div className=\"hidden h-auto w-full grow rounded-md bg-gray-50 md:block\"></div>\n        {/* ② 这个 <form> starter 里已有，只需补 action；按钮部分保持原样 */}\n        <form\n          action={async () => {\n            'use server';\n            await signOut({ redirectTo: '/' });\n          }}\n        >\n          <button className=\"flex h-[48px] w-full grow items-center justify-center gap-2 rounded-md bg-gray-50 p-3 text-sm font-medium hover:bg-sky-100 hover:text-blue-600 md:flex-none md:justify-start md:p-2 md:px-3\">\n            <PowerIcon className=\"w-6\" />\n            <div className=\"hidden md:block\">Sign Out</div>\n          </button>\n        </form>\n      </div>\n    </div>\n  );\n}",
      check: "点 Sign Out 后回到首页 `/`，且已登出；此时再访问 `/dashboard` 会被拦回登录页。",
      pitfalls: [
        "给 `sidenav.tsx` 加 `'use client'` 会让内联 Server Action 失效 —— Server Action 必须定义在服务端组件里。",
        "从 `next-auth/react` 引入 `signOut` 会报错：服务端版要从项目根目录的 `auth.ts` 引入。",
        "内联 Server Action **必须是 `async` 函数**（哪怕体内只有一行），否则 Next 会报「Server Actions must be async functions」类的错误。",
      ],
      note: "⭐ 可选改进（课程不要求）：starter 那句文字用的是 `hidden md:block`，窄屏时等于 `display:none`，按钮就变成没有可读名称的纯图标按钮（屏幕阅读器只读「按钮」）。想修就在 `<PowerIcon />` 旁加 `<span className='sr-only'>Sign Out</span>` —— 与第 13 章「图标按钮要有名字」是同一件事。",
    },
  ],
  tips: [
    "本章内容最多（配置、Action、表单、路由保护四块），建议分两三次完成。",
    "版本差异：middleware.ts → `proxy.ts`；`useFormState` → `useActionState`；`next-auth@beta` 就是 Auth.js v5。报错先确认版本。",
    "⛔ 安全底线：`bcrypt`、`AUTH_SECRET`、数据库连接串只在服务端使用，绝不能被客户端组件引用。",
  ],
};
